name: testing

on:
  push:
    branches: 
      - master
      - fix/*
      - feat/*
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git fetch --force --tags

    - uses: actions/setup-go@v3
      with:
        go-version: ^1.19
        cache: true

    - name: Test
      run: go test ./pkg/... -cover -count=1

